chore(traveller): update yaml and saas to 94 version
ayasofyazilim-clomerce/unirefund-web pull request #55
Opened 2024-12-24 07:50 UTC by yusualhashash

## Description

## How has this been tested?

- [ ] Prod
- [ ] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-12-24 10:15 UTC, ertugrulcan-ays requested changes

2024-12-24 10:15 UTC, ertugrulcan-ays commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/page.tsx
> -  showExpired?: boolean;
are we sure all of these unneccesary

2024-12-24 10:27 UTC, eren-ayasofyazilim requested changes

2024-12-24 10:27 UTC, eren-ayasofyazilim commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/page.tsx
> +  const travellerDetailsData = await getTravellersDetailsApi(travellerId);
const travellerDetailResponse

2024-12-24 10:27 UTC, eren-ayasofyazilim commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/identification/[identificationId]/page.tsx
>    const countries = await getCountriesApi();
const countriesResponse

2024-12-24 10:27 UTC, eren-ayasofyazilim commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/identification/new/page.tsx
> +  const traveller = await getTravellersDetailsApi(travellerId);
const travellerResponse

2024-12-24 10:27 UTC, eren-ayasofyazilim commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/identification/new/page.tsx
>    const countries = await getCountriesApi();
const countriesResponse

2024-12-24 10:32 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/page.tsx
> -  showExpired?: boolean;
yes already the type that i give contain all them but i taked error from split so i convert the type of nationalities and residences from array to string to solve the lint error

export type GetApiTravellerServiceTravellersData = {
    email?: string;
    fullName?: string;
    maxResultCount?: number;
    nationalities?: Array<(string)>;
    phoneNumber?: string;
    residences?: Array<(string)>;
    showExpired?: boolean;
    skipCount?: number;
    sorting?: string;
    travelDocumentNumber?: string;
    username?: string;
};

2024-12-24 12:24 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/page.tsx
> +  const travellerDetailsData = await getTravellersDetailsApi(travellerId);
done

2024-12-24 12:24 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/identification/new/page.tsx
> +  const traveller = await getTravellersDetailsApi(travellerId);
done

2024-12-24 12:24 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/identification/new/page.tsx
>    const countries = await getCountriesApi();
done

2024-12-24 12:24 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/(unirefund)/parties/travellers/[travellerId]/identification/[identificationId]/page.tsx
>    const countries = await getCountriesApi();
done

2024-12-24 12:51 UTC, eren-ayasofyazilim submitted a review, later dismissed

2024-12-25 05:28 UTC, eren-ayasofyazilim approved these changes

2024-12-25 05:33 UTC, ertugrulcan-ays approved these changes

2024-12-25 05:33 UTC, merged